### ISSUE TITLE
False positive for "duplicate hash key detected" on Yaml anchors

### ISSUE THREAD

**Issue by weakcamel** [gdubicki/gitlabform#340] opened 2022-03-08 17:48 UTC
**Describe the bug**

Gitlabform reports >1 Yaml anchors as duplicate keys which is not true.

Such anchors are useful for re-using parts of configuration and are part of Yaml specification so it would be really nice if they were still allowed.

Example:

```
---
# ...

.default_confluence: &default_confluence
  confluence:
    confluence_url: https://....

.default_jira: &default_jira
  jira:
    active: true
    url: https://....

projects_and_groups:
  "group_name/*":
    <<: *default_jira
    <<: *default_confluence
```

Output:

```
Reading config from file: services.yml
ERROR:  Duplicate Hash key detected:  
ERROR:     in "services.yml", line 74, column 5
ERROR:     found duplicate key "<<"
ERROR:     in "services.yml", line 75, column 5
Please try --help for more information.
```

**GitLabForm version**

Output of `gitlabform -V`
```
🏗  GitLabForm version: 2.10.0 = the latest stable 😊
```

**GitLab version**

Any (13.12 in my instance)

**Comment by gdubicki** [comment] 2022-03-08 21:42
Hi @weakcamel!

It turns out that:

```
projects_and_groups:
  "group_name/*":
    <<: *default_jira
    <<: *default_confluence
```

...is not a great syntax  and you should use a syntax like:

```
projects_and_groups:
  "group_name/*":
    <<: [*default_jira, *default_confluence]
```

...instead. Please read more about it [here](https://sourceforge.net/p/ruamel-yaml/tickets/313/) and [here](https://stackoverflow.com/questions/70202180/pre-commit-hooks-yml-validation-fails-when-using-merging-several-anchors).

While I personally think that the former syntax is easier to read and better for `git blame` view (separate line for each "include" entity) I agree with Anthon that the latter is more correct.

I suggest you to change your syntax then, but if we have more people affected by this problem perhaps we can consider making disallowing duplicate keys a feature that you can turn off.

**Comment by weakcamel** [comment] 2022-03-09 08:33
Hello,

Many thanks for the prompt response.

It took me a while to find the right piece of specification (it's a separate document, not included in the general index) but here it is: https://yaml.org/type/merge.html and indeed, merge of multiple multiple dictionaries should be specified as a list.

Which is quite a surprise to me as the other syntax works perfectly fine with Gitlab CI Yaml files.

So yes, I agree it's not a bug.

On a side note, while digging I discovered that the status of merge key type in general is quite unclear: https://ktomk.github.io/writing/yaml-anchor-alias-and-merge-key.html - interesting times... :)

**Comment by gdubicki** [comment] 2022-03-12 09:35
Whoa, thanks for sharing these @weakcamel! It's even more complicated than I thought! My initial thought is that this means that we should NOT switch gitlabform to YAML 1.2 then.

**Comment by gdubicki** [comment] 2022-04-25 11:44
Closing this as it's not a bug. Please reopen if needed, @weakcamel.

**Closed by gdubicki** 2022-04-25 11:44 UTC
