### ISSUE TITLE
400 Response Code When Setting a User With "No Access" Access Level

### ISSUE THREAD

**Issue by ep-linden** [gdubicki/gitlabform#328] opened 2022-01-22 01:32 UTC
**Bug**
At the group level, I am setting members like this:

```YAML
members:
  enforce: true
  groups:
    group1:
      group_access: developer
    group2:
      group_access: developer
    group3:
      group_access: developer
```

However, I don't want one of the projects in the group to inherit the same groups. So at the project level, I set those groups with `no access` like this:

```YAML
members:
  groups:
    group4:
      group_access: maintainer
    group1:
      group_access: no access
    group2:
      group_access: no access
    group3:
      group_access: no access
```

Then when I run GitLabForm, the groups are removed, but I receive this error message:

```shell
Request url='https://gitlab.example.com//api/v4/projects/id/members', method=POST, data='{"access_level": 0, "expires_at": null, "user_id": 8}' failed - expected code(s) [201], got code 400 & body: '{"message":{"access_level":["is not included in the list"]}}'

Traceback (most recent call last):
  File "/gitlabform/gitlabform/core.py", line 428, in run
    self.project_processors.process_entity(
  File "/gitlabform/gitlabform/processors/__init__.py", line 30, in process_entity
    processor.process(
  File "/gitlabform/gitlabform/processors/util/decorators.py", line 42, in method_wrapper
    return method(self, project_and_group, SafeDict(configuration), *args)
  File "/gitlabform/gitlabform/processors/abstract_processor.py", line 48, in process
    self._process_configuration(project_or_project_and_group, configuration)
  File "/gitlabform/gitlabform/processors/project/members_processor.py", line 31, in _process_configuration
    self._process_users(project_and_group, users, enforce_members)
  File "/gitlabform/gitlabform/processors/project/members_processor.py", line 127, in _process_users
    self.gitlab.add_member_to_project(
  File "/gitlabform/gitlabform/gitlab/members.py", line 34, in add_member_to_project
    return self._make_requests_to_api(
  File "/gitlabform/gitlabform/gitlab/core.py", line 130, in _make_requests_to_api
    response = self._make_request_to_api(
  File "/gitlabform/gitlabform/gitlab/core.py", line 221, in _make_request_to_api
    raise UnexpectedResponseException(
gitlabform.gitlab.core.UnexpectedResponseException: Request url='https://gitlab.example.com//api/v4/projects/id/members', method=POST, data='{"access_level": 0, "expires_at": null, "user_id": 8}' failed - expected code(s) [201], got code 400 & body: '{"message":{"access_level":["is not included in the list"]}}'
```

Just in case it was not clear, I used `example` and `id` as placeholders to hide some information in the  Request URLs.

**Expectation**
I am expecting the groups to be deleted without any error. 

**GitLabForm version**
2.10.0

**GitLab version**
 14.5.2-ee

**Comment by gdubicki** [comment] 2022-02-02 20:47
Hi @ep-linden!

I think that if we would implement #326, then you could achieve what you want by configuring that single project using the "don't inherit configs for this section" keyword for the `members` section.

I will close this issue as a duplicate of that one then, but feel free to please reopen if I got you wrong!

**Closed by gdubicki** 2022-02-02 20:47 UTC
Labels: 🐛bug
